{% set version = "3.0" %}

package:
  name: zip
  version: {{ version }}

source:
  # patches as applied in
  # https://gitlab.archlinux.org/archlinux/packaging/packages/zip/-/blob/main/PKGBUILD?ref_type=heads
  - url: https://src.fedoraproject.org/rpms/zip/raw/rawhide/f/zip-3.0-currdir.patch
    sha256: 44cac3d4e8b447988b6e4eeb4bb6e701110cedfb09ea49eac471011328c8acab
  - url: https://src.fedoraproject.org/rpms/zip/raw/rawhide/f/zip-3.0-exec-shield.patch
    sha256: 10f0f3756a2415e33edf1455373b322404962b743b3a52a757b669e47dd7f1b2
  - url: https://src.fedoraproject.org/rpms/zip/raw/rawhide/f/zip-3.0-format-security.patch
    sha256: 3759134487afad9c63e2e9693aa05b9dcc67f55a9ef961e82074b587b094292a
  - url: https://src.fedoraproject.org/rpms/zip/raw/rawhide/f/zipnote.patch
    sha256: 89249a3f1fdf838b795ce432a2d763fdbe913d6a146541e41b7a2e2769291ba0
  - url: https://downloads.sourceforge.net/infozip/zip{{ version.replace(".", "") }}.tar.gz
    sha256: f0e8bb1f9b7eb0b01285495a2699df3a4b766784c1765a8f1aeedf63c0806369
    patches:
      # Here, we need single quotes because SRC_DIR on win has backslashes
      - '{{ SRC_DIR }}/zip-3.0-currdir.patch'
      - '{{ SRC_DIR }}/zip-3.0-exec-shield.patch'
      - '{{ SRC_DIR }}/zip-3.0-format-security.patch'
      - '{{ SRC_DIR }}/zipnote.patch'
      - cr-define.patch  # [win]

build:
  number: 4

requirements:
  build:
    - {{ compiler('c') }}
    - make  # [unix]
    - sed  # [unix]
    - autotools_clang_conda  # [win]

test:
  commands:
    {% for bin in ["zip", "zipcloak", "zipnote", "zipsplit"] %}
    - which {{ bin }}
    - which {{ bin }} | grep "${PREFIX}"
    - {{ bin }} -h
    {% endfor %}

about:
  home: https://infozip.sourceforge.net
  license: LicenseRef-Info-ZIP
  license_file: LICENSE
  summary: simple program for unzipping files
  dev_url: https://sourceforge.net/projects/infozip

extra:
  recipe-maintainers:
    - msarahan
    - jerowe
    - bollwyvl
    - zklaus
